### ISSUE TITLE
INJECTION_ERROR: Injection failed on ValidationPipe > Ajv

### ISSUE THREAD

**Issue by zj05409** [borjapazr/express-typescript-skeleton#273]
Environment:

computer: macbook pro
os: MacOS Monterey
node version: v18.12.1
npm version: v8.19.2
yarn version: 1.22.18

To reproduce:

git checkout v2.2.2
git switch -c dev
yarn
yarn prisma:generate
yarn run dev

Then I get the output:

[2023-01-07 03:07:11.711] ERROR uncaughtException: Injection failed on ValidationPipe > Ajv
Origin: Cannot read properties of undefined (reading 'code')
INJECTION_ERROR: Injection failed on ValidationPipe > Ajv
Origin: Cannot read properties of undefined (reading 'code')
    at Function.throwInjectorError (/Users/zhangjie/Work/express-typescript-skeleton/node_modules/@tsed/di/src/errors/InjectionError.ts:44:11)
    at InjectorService.resolve (/Users/zhangjie/Work/express-typescript-skeleton/node_modules/@tsed/di/src/services/InjectorService.ts:640:22)
    at InjectorService.invoke (/Users/zhangjie/Work/express-typescript-skeleton/node_modules/@tsed/di/src/services/InjectorService.ts:211:21)
    at InjectorService.loadSync (/Users/zhangjie/Work/express-typescript-skeleton/node_modules/@tsed/di/src/services/InjectorService.ts:264:14)
    at InjectorService.load (/Users/zhangjie/Work/express-typescript-skeleton/node_modules/@tsed/di/src/services/InjectorService.ts:336:10)
    at async PlatformBuilder.loadInjector (/Users/zhangjie/Work/express-typescript-skeleton/node_modules/@tsed/common/src/builder/PlatformBuilder.ts:202:5)
    at async PlatformBuilder.runLifecycle (/Users/zhangjie/Work/express-typescript-skeleton/node_modules/@tsed/common/src/builder/PlatformBuilder.ts:189:5)
    at async start (/Users/zhangjie/Work/express-typescript-skeleton/src/index.ts:13:20) INJECTION_ERROR: Injection failed on ValidationPipe > Ajv
Origin: Cannot read properties of undefined (reading 'code')
    at Function.throwInjectorError (/Users/zhangjie/Work/express-typescript-skeleton/node_modules/@tsed/di/src/errors/InjectionError.ts:44:11)
    at InjectorService.resolve (/Users/zhangjie/Work/express-typescript-skeleton/node_modules/@tsed/di/src/services/InjectorService.ts:640:22)
    at InjectorService.invoke (/Users/zhangjie/Work/express-typescript-skeleton/node_modules/@tsed/di/src/services/InjectorService.ts:211:21)
    at InjectorService.loadSync (/Users/zhangjie/Work/express-typescript-skeleton/node_modules/@tsed/di/src/services/InjectorService.ts:264:14)
    at InjectorService.load (/Users/zhangjie/Work/express-typescript-skeleton/node_modules/@tsed/di/src/services/InjectorService.ts:336:10)
    at async PlatformBuilder.loadInjector (/Users/zhangjie/Work/express-typescript-skeleton/node_modules/@tsed/common/src/builder/PlatformBuilder.ts:202:5)
    at async PlatformBuilder.runLifecycle (/Users/zhangjie/Work/express-typescript-skeleton/node_modules/@tsed/common/src/builder/PlatformBuilder.ts:189:5)
    at async start (/Users/zhangjie/Work/express-typescript-skeleton/src/index.ts:13:20)
[nodemon] clean exit - waiting for changes before restart

**Comment by borjapazr** [comment]
Hello, @zj05409 👋

Thank you very much for opening this issue. In the latest version [2.3.1](https://github.com/borjapazr/express-typescript-skeleton/tree/v2.3.1) it has been fixed. The problem was that a dependency was missing, namely `Ajv`, which should appear explicitly in the `package.json`. Although `@tsed/ajv` is installed, this does not imply that `Ajv` is also installed.

As the project uses `npm` as the main package manager, it had never been tested with `yarn`. Each package manager installs the dependencies in a different way and, because of this, with `npm` it worked and with `yarn` it did not.

If you detect any other problem, do not hesitate to open another issue.

Thanks again.

Regards.
